// Static soap product data - rich content for the store
export const soaps = [
  {
    _id: "soap_001",
    name: "Rose Petal Bliss",
    slug: "rose-petal-bliss",
    shortDescription: "Hydrating & romantic — skin that feels like petals",
    description:
      "Handcrafted with real dried rose petals and Bulgarian rose essential oil, this soap deeply moisturises and gently exfoliates. Shea butter locks in moisture while kaolin clay sweeps away impurities. Your skin is left silky-soft with a delicate floral scent that lingers all day.",
    price: 349,
    discountPrice: 299,
    stock: 50,
    images: [{ url: "https://images.unsplash.com/photo-1600857062241-98e5dba7f3c6?w=600", publicId: "rose" }],
    ingredients: "Coconut Oil, Palm Oil, Shea Butter, Rose Essential Oil, Kaolin Clay, Dried Rose Petals, Castor Oil",
    weight: "100g",
    scent: "Bulgarian Rose",
    category: { name: "Floral", slug: "floral" },
    isFeatured: true,
    isActive: true,
    ratings: { average: 4.9, count: 127 },
    benefits: ["Deep Hydration", "Gentle Exfoliation", "Anti-inflammatory", "Mood Lifting"],
    howToUse: "Lather between wet palms and massage gently onto damp skin in circular motions. Leave for 30 seconds, then rinse well. Use daily for glowing skin.",
    skinType: "All skin types, especially dry and sensitive",
  },
  {
    _id: "soap_002",
    name: "Lavender Dream",
    slug: "lavender-dream",
    shortDescription: "Calming & stress-relief — your bedtime ritual",
    description:
      "Pure French lavender essential oil blended with oat milk and chamomile extract creates the ultimate wind-down soap. Clinically proven to reduce cortisol levels, it calms anxious skin and anxious minds alike. Gentle enough for nightly use, luxurious enough to be your favourite self-care treat.",
    price: 329,
    discountPrice: 279,
    stock: 45,
    images: [{ url: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600", publicId: "lavender" }],
    ingredients: "Oat Milk, Lavender Essential Oil, Chamomile Extract, Shea Butter, Coconut Oil, Dried Lavender Buds",
    weight: "100g",
    scent: "French Lavender & Chamomile",
    category: { name: "Calming", slug: "calming" },
    isFeatured: true,
    isActive: true,
    ratings: { average: 4.8, count: 98 },
    benefits: ["Stress Relief", "Better Sleep", "Soothes Irritation", "Deeply Calming"],
    howToUse: "Use in the evening as part of your wind-down routine. The lavender aroma activates your parasympathetic nervous system — breathe deeply while lathering for maximum relaxation.",
    skinType: "Sensitive, reactive, and stressed skin",
  },
  {
    _id: "soap_003",
    name: "Charcoal Detox",
    slug: "charcoal-detox",
    shortDescription: "Deep cleanse & pore-purifying — the glow-up soap",
    description:
      "Activated bamboo charcoal acts like a magnet, pulling out toxins, excess oil, and environmental pollutants from deep within your pores. Tea tree oil fights acne-causing bacteria while aloe vera soothes post-cleanse. The result? Visibly clearer, mattified skin in just 2 weeks.",
    price: 379,
    discountPrice: null,
    stock: 35,
    images: [{ url: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600", publicId: "charcoal" }],
    ingredients: "Activated Bamboo Charcoal, Tea Tree Essential Oil, Aloe Vera, Coconut Oil, Castor Oil, Kaolin Clay",
    weight: "100g",
    scent: "Fresh & Earthy",
    category: { name: "Detox", slug: "detox" },
    isFeatured: true,
    isActive: true,
    ratings: { average: 4.7, count: 214 },
    benefits: ["Pore Cleansing", "Oil Control", "Acne Fighting", "Detoxifying"],
    howToUse: "Perfect as a morning cleanse. Wet your face or body, lather the soap, apply to skin in small circles and leave for 60 seconds. Rinse thoroughly with warm water.",
    skinType: "Oily, acne-prone, and combination skin",
  },
  {
    _id: "soap_004",
    name: "Turmeric Glow",
    slug: "turmeric-glow",
    shortDescription: "Brightening & anti-dark-spot — your golden hour",
    description:
      "Ancient Ayurvedic wisdom meets modern skincare. Raw turmeric and saffron work together to fade dark spots, hyperpigmentation, and uneven skin tone. Vitamin C-rich rosehip oil accelerates cell renewal for a radiant, lit-from-within glow. Tested: 89% noticed brighter skin in 3 weeks.",
    price: 399,
    discountPrice: 349,
    stock: 28,
    images: [{ url: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600", publicId: "turmeric" }],
    ingredients: "Raw Turmeric, Saffron Extract, Rosehip Oil, Vitamin C, Kojic Acid, Coconut Oil, Shea Butter",
    weight: "100g",
    scent: "Warm Spice & Citrus",
    category: { name: "Brightening", slug: "brightening" },
    isFeatured: true,
    isActive: true,
    ratings: { average: 4.9, count: 183 },
    benefits: ["Brightening", "Dark Spot Fading", "Even Skin Tone", "Anti-aging"],
    howToUse: "For best results, use every morning. Leave lather on skin for 1–2 minutes before rinsing. Follow with SPF 30+ during the day when using brightening soaps.",
    skinType: "Dull, uneven, and hyperpigmented skin",
  },
  {
    _id: "soap_005",
    name: "Oat & Honey Gentle",
    slug: "oat-honey-gentle",
    shortDescription: "Nourishing & baby-soft — for the sensitive souls",
    description:
      "Colloidal oatmeal — the gold standard in sensitive-skin care — paired with raw honey and goat milk creates a soap so gentle, it's recommended by dermatologists. It relieves eczema flares, restores the skin barrier, and provides 12-hour moisture. Your most delicate skin, loved deeply.",
    price: 319,
    discountPrice: 269,
    stock: 60,
    images: [{ url: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600", publicId: "oat" }],
    ingredients: "Colloidal Oatmeal, Raw Honey, Goat Milk, Chamomile Extract, Vitamin E, Coconut Oil, Olive Oil",
    weight: "100g",
    scent: "Honey & Vanilla",
    category: { name: "Gentle", slug: "gentle" },
    isFeatured: false,
    isActive: true,
    ratings: { average: 4.8, count: 156 },
    benefits: ["Eczema Relief", "Barrier Repair", "12hr Moisture", "Dermatologist Tested"],
    howToUse: "Safe for face and body. Use twice daily. For eczema, apply to affected areas and allow 60 seconds contact time. Gentle enough for children over 3 years.",
    skinType: "Dry, sensitive, eczema-prone skin",
  },
  {
    _id: "soap_006",
    name: "Citrus Burst",
    slug: "citrus-burst",
    shortDescription: "Energising & uplifting — your morning wake-up call",
    description:
      "A zesty explosion of cold-pressed orange, lemon, and grapefruit essential oils combined with invigorating peppermint. Vitamin C-rich citrus extracts boost collagen production while the fresh, uplifting scent kicks your brain into morning mode — no coffee needed.",
    price: 299,
    discountPrice: null,
    stock: 40,
    images: [{ url: "https://images.unsplash.com/photo-1575506427498-ec65e64c68cd?w=600", publicId: "citrus" }],
    ingredients: "Orange Essential Oil, Lemon Essential Oil, Grapefruit Extract, Peppermint, Vitamin C, Coconut Oil",
    weight: "100g",
    scent: "Fresh Citrus & Mint",
    category: { name: "Energising", slug: "energising" },
    isFeatured: false,
    isActive: true,
    ratings: { average: 4.6, count: 89 },
    benefits: ["Energising", "Mood Boost", "Collagen Support", "Antioxidant Rich"],
    howToUse: "Best used in morning showers. Breathe in the citrus steam for an instant energy boost. Perfect for cold mornings when you need that extra push to start your day.",
    skinType: "Normal and combination skin",
  },
];

export const benefits = [
  { icon: "🌿", title: "100% Natural", desc: "No sulfates, parabens, or synthetic fragrances. Just pure, plant-powered goodness." },
  { icon: "🤲", title: "Handcrafted", desc: "Made in small batches with intention and care. Every bar is unique, just like you." },
  { icon: "🐰", title: "Cruelty Free", desc: "Never tested on animals. Certified vegan ingredients across our entire range." },
  { icon: "🌍", title: "Eco Packaging", desc: "Plastic-free, compostable wrapping. Your skin AND the planet thank you." },
  { icon: "✨", title: "Dermatologist Tested", desc: "Every formula clinically tested for safety on all skin types including sensitive." },
  { icon: "💛", title: "Made with Love", desc: "Small-batch production means more attention, better quality, and real results." },
];

export const testimonials = [
  { name: "Priya S.", handle: "@priya.glows", text: "The Rose Petal Bliss literally changed my skin. Been using it for 3 weeks and the texture is unreal 🌸", rating: 5, soap: "Rose Petal Bliss" },
  { name: "Arjun K.", handle: "@arjun.skincare", text: "Charcoal Detox got rid of my blackheads in like 10 days??? My dermatologist was shook 😭", rating: 5, soap: "Charcoal Detox" },
  { name: "Meera T.", handle: "@meera.t", text: "Lavender Dream is my sleep ritual now. I literally cannot go to bed without it. The smell is HEAVEN", rating: 5, soap: "Lavender Dream" },
  { name: "Rohan V.", handle: "@rohan.v", text: "Turmeric Glow faded my dark spots in a month. I'm obsessed. My family wants to know my secret lol", rating: 5, soap: "Turmeric Glow" },
];
